#!/usr/bin/env python3
"""Is there a level difference between the two power fields with no load transition at all?

Phase E5 put exactly one rise and one fall inside every sampling window, so "a fixed quantity
per window" and "a fixed quantity per pair of transitions" are perfectly collinear in it: the
count of windows and the count of pairs are the same number. No analysis of E5 can separate
them. This is the cell E5 could not contain -- windows with NO transition -- and it separates
one more thing besides, because a window's length is varied while its content is not:

    a DC difference x duration   scales with the window: 28 s gives four times what 7 s gives
    a fixed per-window term      does not

A linear filter cannot produce either. Integrating a filtered signal over a window loses
exactly `m x (end level - start level)` whatever happens inside, and on a flat idle trace the
two ends are the same level, so every LTI filter predicts zero. Anything found here is a
property of the readout paths and not of their time behaviour.

  idle_offset.py                      report from the committed measurement
  idle_offset.py --measure --out F    take a new one; holds the GPU, so take the lock

THE MEASUREMENT IS NOT REGENERATED BY THE REPORT. `analysis/idle_offset_raw.json` is data, and
the report is a pure function of it, which is what lets `verify_everything.sh` rebuild the
report byte for byte without a GPU.
"""
from __future__ import annotations

import argparse
import json
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
RAW = ROOT / "analysis" / "idle_offset_raw.json"
OUT = ROOT / "analysis" / "idle_offset.txt"


def measure(out_path: Path, secs=(7.0, 14.0, 28.0), n=6, interval_s=0.10) -> None:
    """Take fresh windows. Holds the GPU for minutes; the CPU guard's lock applies."""
    import time
    sys.path.insert(0, str(Path(__file__).parent))
    import telemetry as T
    rows = []
    for s in secs:
        for i in range(n):
            with T.sampling(0, interval_s=interval_s) as smp:
                time.sleep(s)
            d = smp.summary()
            if not (d.get("energy_j") and d.get("energy_j_instant")):
                continue
            rows.append({"label": "bare", "want_s": s,
                         "off": d["energy_j_instant"] - d["energy_j"],
                         "span": d["sample_span_s"], "mean": d["power_mean_w"],
                         "sd": d.get("power_sd_w"), "n": d.get("n_power_samples"),
                         "e_avg": d["energy_j"], "nvml": d.get("energy_j_nvml")})
            print(f"  {s:5.1f}s {i + 1}/{n}  {rows[-1]['off']:+7.3f} J", flush=True)
    out_path.write_text(json.dumps({"schema": "idle-offset/1", "records": rows}, indent=1))


def report(raw: dict) -> str:
    L: list[str] = []
    W = L.append
    rows = raw["records"]
    W("=" * 92)
    W("THE TWO POWER FIELDS ON A WINDOW WITH NO LOAD TRANSITION IN IT")
    W("=" * 92)
    W(raw.get("what", ""))
    W("")
    W(f"{len(rows)} windows, sampler interval {raw.get('interval_s')} s, "
      f"{raw.get('gpu', '?')} on {raw.get('host', '?')}, {raw.get('captured_at', '?')}.")
    for k, v in sorted((raw.get("levels") or {}).items()):
        W(f"  {k:12s} {v}")
    W("")
    W(f"  {'level':12s} {'asked s':>8s} {'n':>4s} {'span s':>8s} {'mean W':>8s} "
      f"{'offset J':>9s} {'offset W':>9s} {'sd J':>7s}")
    W("  " + "-" * 78)
    for lab in sorted({r["label"] for r in rows}):
        for s in sorted({r["want_s"] for r in rows if r["label"] == lab}):
            v = [r for r in rows if r["label"] == lab and abs(r["want_s"] - s) < 0.01]
            o = [r["off"] for r in v]
            W(f"  {lab:12s} {s:8.1f} {len(v):4d} {st.fmean(r['span'] for r in v):8.2f} "
              f"{st.fmean(r['mean'] for r in v):8.1f} {st.fmean(o):9.3f} "
              f"{st.fmean(r['off'] / r['span'] for r in v):+9.3f} "
              f"{st.stdev(o) if len(o) > 1 else float('nan'):7.3f}")
    W("")
    # The one cell that is not a measurement of idle, said so rather than dropped quietly.
    bad = [r for r in rows if r["mean"] > 40.0]
    if bad:
        labs = sorted({(r["label"], r["want_s"]) for r in bad})
        W("  NOT AN IDLE MEASUREMENT, and left in the table rather than dropped: "
          + ", ".join(f"{a} at {b:g} s" for a, b in labs) + ". The server had just been")
        W("  started and the card was still coming down from loading 16 GB of weights; the")
        W("  windows opened 5 s after the health check passed, which was not enough. Its mean")
        W("  power says so -- twice the idle floor -- and its offset has the other sign.")
        W("")
    good = [r for r in rows if r["mean"] <= 40.0]
    if good:
        wpr = [r["off"] / r["span"] for r in good]
        W(f"  Over the {len(good)} windows that are idle: the offset is "
          f"{st.fmean(wpr):+.3f} W, spread {max(wpr) - min(wpr):.3f}, and the JOULES scale "
          f"with the window while")
        W("  the WATTS do not. So it is a level difference between the two readout paths, not")
        W("  a per-window quantity -- and not a filter, because no linear filter can put")
        W("  anything at all on a window whose two ends sit at the same level.")
        W("")
        W("  WHAT THIS DOES NOT ESTABLISH. It is measured at the idle floor, about 28 W, and")
        W("  a resident model does not raise that floor: a server holding 16 GB and answering")
        W("  nothing sits at the same 28 W as a bare card. Phase E5's windows idle at about")
        W("  128 W between requests, which is therefore NOT steady idle but a card still on")
        W("  its way down, and this measurement says nothing about the offset there. Against")
        W("  it, `results/phase_e.json`'s 150 W arms hold a nearly flat trace for 44.8 s and")
        W("  show 0.596 J of offset in total, which bounds the difference at that level to")
        W("  about 0.013 W. Whatever this is, it is large at the floor and small under load,")
        W("  and the levels in between are not measured.")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--measure", action="store_true")
    ap.add_argument("--out", default=str(RAW))
    ap.add_argument("--stdout", action="store_true")
    a = ap.parse_args()
    if a.measure:
        measure(Path(a.out))
        return 0
    text = report(json.loads(RAW.read_text()))
    if a.stdout:
        sys.stdout.write(text)
    else:
        tmp = OUT.with_suffix(".txt.tmp")
        tmp.write_text(text)
        tmp.replace(OUT)
        print(f"   wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
